ENT.Base = "base_ai" -- This entity is based on "base_ai"
ENT.Type = "ai" -- What type of entity is it, in this case, it's an AI.
ENT.PrintName		= "Product Buyer"
ENT.Author			= "Spectrum"
ENT.Contact			= "N/A"
ENT.Purpose			= "Buys your socks, I mean stocks!"
ENT.Instructions	= "Press E"
ENT.Category 		= "Universal Union"
ENT.Spawnable       = true
